name: C/C++ CI

on: 
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo apt update
        sudo apt install libgtest-dev dnsperf
    - name: make
      run: |
        make all -j4
        make clean
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
          name: my-build-apk
          path: ./**/*.apk
